fix shellcheck warnings about unquoted args

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -1,8 +1,8 @@
 #!/bin/bash
-cd "$(dirname "$0")"
+cd "$(dirname "$0")" || exit
 
 die() {
-  echo >&2 $1
+  echo >&2 "$1"
   exit 1
 }
 
@@ -12,31 +12,31 @@ usage() {
 }
 
 extract() {
-    local deb=`readlink -f $1`
+    local deb=$(readlink -f "$1")
     local out=$2
     if [ ! -d "$out" ]; then
-        mkdir $out
+        mkdir "$out"
     fi
-    local tmp=`mktemp -d`
+    local tmp=$(mktemp -d)
 
-    cd $tmp
-    ar xv $deb || die "ar failed"
+    cd "$tmp" || exit
+    ar xv "$deb" || die "ar failed"
     if [ -f "data.tar.zst" ];then
         tar -I zstd -xf data.tar.* || die "tar failed"
     else
         tar xf data.tar.* || die "tar failed"
     fi
-    cd -
+    cd - || exit
 
-    cp -rP $tmp/lib/*/* $out 2>/dev/null \
-      || cp -rP $tmp/lib32/* $out 2>/dev/null \
-      || cp -rP $tmp/usr/lib/*/* $out 2>/dev/null \
-      || cp -rP $tmp/usr/lib/debug/lib/*/* $out 2>/dev/null \
-      || cp -rP $tmp/usr/lib/debug/lib32/* $out 2>/dev/null \
-      || cp -rP $tmp/usr/lib/debug/.build-id $out 2>/dev/null \
+    cp -rP "$tmp"/lib/*/* "$out" 2>/dev/null \
+      || cp -rP "$tmp"/lib32/* "$out" 2>/dev/null \
+      || cp -rP "$tmp"/usr/lib/*/* "$out" 2>/dev/null \
+      || cp -rP "$tmp"/usr/lib/debug/lib/*/* "$out" 2>/dev/null \
+      || cp -rP "$tmp"/usr/lib/debug/lib32/* "$out" 2>/dev/null \
+      || cp -rP "$tmp"/usr/lib/debug/.build-id "$out" 2>/dev/null \
       || die "Failed to save. Check it manually $tmp"
 
-    rm -rf $tmp
+    rm -rf "$tmp"
 }
 
 if [[ $# -ne 2 ]]; then
@@ -44,5 +44,3 @@ if [[ $# -ne 2 ]]; then
 fi
 
 extract "$1" "$2"
-
-
