minor shellcheck fixes

diff --git a/unstrip b/unstrip
--- a/unstrip
+++ b/unstrip
@@ -11,34 +11,34 @@ if [[ $# != 1 ]]; then
   usage
 fi
 
-path=$(realpath $1)
+path=$(realpath "$1")
 dirp=$(dirname "$path")
 echo "path = $path"
 # echo "$dirp"
 
 # sanity check
 if file "$path" | grep -q debug_info; then
-	echo >&2 "file already has debug_info. quitting!"
-	exit 1
+    echo >&2 "file already has debug_info. quitting!"
+    exit 1
 fi
 
 bid=$(eu-readelf -n "$path" | awk '/Build ID/ {print $3}')
 echo "Build ID = $bid"
 
 if [[ ${#bid} -lt 40 ]]; then
-	echo >&2 "invalid buildid"
-	exit 1
+    echo >&2 "invalid buildid"
+    exit 1
 fi
 
 dbg_dir=$dirp/.debug/
 # echo "cmd: " find "$dbg_dir" -name "*"${bid:2:48}"*"
-dbgfile=$(find "$dbg_dir" -name "*"${bid:2:48}"*")
+dbgfile=$(find "$dbg_dir" -name "*""${bid:2:48}""*")
 echo "dbgfile = $dbgfile"
 
 if [[ -z $dbgfile ]]; then
-	echo >&2 "debuginfo not found"
-	exit 1
+    echo >&2 "debuginfo not found"
+    exit 1
 fi
 
-eu-unstrip $path $dbgfile
-ln -f $dbgfile $path
+eu-unstrip "$path" "$dbgfile"
+ln -f "$dbgfile" "$path"
